import gsap from 'gsap';
import { TOOLS } from '../data/tools.js';

// Mock AI responses for demo
const MOCK_RESPONSES = {
  chatgpt: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>NovaMind AI</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0a0a0a; color: #fff;
           font-family: system-ui; }
    .hero { height: 100vh; display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center; }
    .hero h1 { font-size: 4rem;
               background: linear-gradient(135deg, #00f0ff, #7c3aed);
               -webkit-background-clip: text;
               -webkit-text-fill-color: transparent; }
    .hero p { color: #888; margin-top: 1rem; }
    .cta { margin-top: 2rem; padding: 14px 32px;
           background: #7c3aed; border: none;
           color: #fff; border-radius: 12px;
           font-size: 1rem; cursor: pointer; }
  </style>
</head>
<body>
  <section class="hero">
    <h1>NovaMind AI</h1>
    <p>The future of intelligence, today.</p>
    <button class="cta">Get Started Free</button>
  </section>
</body>
</html>`,

  claude: `Here's a structured approach for your landing page:

## Architecture
1. **Hero Section** - Full viewport with animated gradient
2. **Features Grid** - 3-column bento layout
3. **Pricing Cards** - Glassmorphism design
4. **CTA Footer** - Final conversion point

## Key Recommendations
- Use \`prefers-reduced-motion\` for accessibility
- Implement dark/light toggle with CSS variables
- Load hero animation after critical CSS

## Code Structure
\`\`\`
src/
├── components/
│   ├── Hero.tsx
│   ├── Features.tsx
│   └── Pricing.tsx
├── styles/
│   └── globals.css
└── App.tsx
\`\`\`

Shall I generate the full implementation?`,

  gemini: `# AI Startup Landing Page Design

## Color Palette
- Primary: #0a0a0a (background)
- Accent: #00d4ff (cyan glow)
- Secondary: #7c3aed (purple)
- Text: #ffffff / #888888

## Sections
1. **Hero**: Animated particle background + gradient text
2. **Social Proof**: Logo carousel
3. **Features**: Bento grid with glassmorphism cards
4. **Pricing**: 3 tiers with popular badge
5. **Footer**: Newsletter + social links

## Animation Stack
- GSAP ScrollTrigger for scroll reveals
- Lenis for smooth scrolling
- CSS @keyframes for ambient effects

## Performance Notes
- Use WebP images
- Lazy load below-fold sections
- Preconnect to font CDN`,

  midjourney: `🎨 Image Generation Result

**Prompt interpreted as:** Dark futuristic AI startup landing page hero section

**Generated concept:**
A sleek, dark-themed hero section featuring:
- Abstract neural network visualization in cyan/purple
- Floating 3D geometric shapes with glass reflections
- Subtle particle effects in the background
- Clean typography with gradient highlights
- Depth-of-field blur effect on edges

**Style:** Cyberpunk minimal, inspired by Apple's dark UI
**Aspect ratio:** 16:9
**Quality:** High detail, 4K ready

→ 4 variations generated. Use /upscale to enhance.`,

  'github-copilot': `// Generated by GitHub Copilot
// AI Startup Landing Page - Hero Component

import { useEffect, useRef } from 'react';
import gsap from 'gsap';

export function Hero() {
  const titleRef = useRef(null);

  useEffect(() => {
    gsap.from(titleRef.current, {
      y: 60,
      opacity: 0,
      duration: 1.2,
      ease: 'power4.out',
    });
  }, []);

  return (
    <section className="hero">
      <div className="hero-bg">
        <canvas id="particles" />
      </div>
      <h1 ref={titleRef}>
        Build the Future with
        <span className="gradient-text"> AI</span>
      </h1>
      <p>Next-generation intelligence platform</p>
      <div className="hero-cta">
        <button className="btn-primary">
          Start Free Trial
        </button>
        <button className="btn-ghost">
          Watch Demo →
        </button>
      </div>
    </section>
  );
}`,
};

// Default response for tools without specific mock
const DEFAULT_RESPONSE = `✨ AI Response Generated

This is a simulated response from the selected AI tool.
In a production environment, this would connect to the
actual API and return real results.

The response would typically include:
- Formatted text or code output
- Token usage statistics
- Processing time metrics
- Model version information

Try selecting different tools to see varied response formats!`;

let selectedTool = null;

export function initPlayground() {
  _renderToolList();
  _initPromptInteraction();
  _checkUrlParams();
}

function _renderToolList() {
  const list = document.getElementById('pgToolList');
  if (!list) return;

  // Group tools that work well in playground
  const playgroundTools = TOOLS.filter(t =>
    ['chatbot', 'code', 'image'].includes(t.category)
  );

  list.innerHTML = playgroundTools.map(tool => `
    <button class="pg-tool-btn" data-tool-id="${tool.id}">
      <span class="pg-tool-icon" style="background: ${tool.color}20; color: ${tool.color};">${tool.icon}</span>
      <span class="pg-tool-name">${tool.name}</span>
    </button>
  `).join('');

  list.addEventListener('click', (e) => {
    const btn = e.target.closest('.pg-tool-btn');
    if (!btn) return;

    const toolId = btn.dataset.toolId;
    _selectTool(toolId);

    list.querySelectorAll('.pg-tool-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
  });
}

function _selectTool(toolId) {
  selectedTool = TOOLS.find(t => t.id === toolId);
  if (!selectedTool) return;

  // Update info panel
  const info = document.getElementById('pgToolInfo');
  if (info) {
    info.innerHTML = `
      <div class="pg-info-card">
        <h4>${selectedTool.name}</h4>
        <p>${selectedTool.description}</p>
        <div class="pg-info-tags">
          ${selectedTool.tags.map(t => `<span>${t}</span>`).join('')}
        </div>
      </div>
    `;
    gsap.from(info, { y: 10, opacity: 0, duration: 0.3, ease: 'power2.out' });
  }

  // Update model badge
  const badge = document.getElementById('pgModelBadge');
  if (badge) {
    badge.innerHTML = `
      <span class="pg-model-dot" style="background: ${selectedTool.color};"></span>
      <span>${selectedTool.name}</span>
    `;
  }

  // Update terminal title
  const title = document.getElementById('pgTerminalTitle');
  if (title) title.textContent = `Prompt → ${selectedTool.name}`;

  // Enable send button
  const btn = document.getElementById('pgSendBtn');
  if (btn) btn.disabled = false;
}

function _initPromptInteraction() {
  const sendBtn = document.getElementById('pgSendBtn');
  const textarea = document.getElementById('pgTextarea');
  if (!sendBtn || !textarea) return;

  sendBtn.addEventListener('click', () => {
    if (!selectedTool || !textarea.value.trim()) return;
    _generateResponse(textarea.value.trim());
  });

  // Ctrl+Enter to send
  textarea.addEventListener('keydown', (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
      if (selectedTool && textarea.value.trim()) {
        _generateResponse(textarea.value.trim());
      }
    }
  });
}

function _generateResponse(prompt) {
  const outputContent = document.getElementById('pgOutputContent');
  const outputMeta = document.getElementById('pgOutputMeta');
  const sendBtn = document.getElementById('pgSendBtn');
  if (!outputContent) return;

  // Show loading state
  sendBtn.disabled = true;
  sendBtn.textContent = 'Generating...';
  outputContent.innerHTML = `
    <div class="pg-loading">
      <div class="pg-loading-dots">
        <span></span><span></span><span></span>
      </div>
      <p>Generating response...</p>
    </div>
  `;

  // Simulate API delay
  const delay = 800 + Math.random() * 1200;
  setTimeout(() => {
    const response = MOCK_RESPONSES[selectedTool.id] || DEFAULT_RESPONSE;
    const tokens = Math.floor(200 + Math.random() * 800);
    const time = (delay / 1000).toFixed(1);

    // Detect if response is code
    const isCode = response.trim().startsWith('<!') ||
                   response.trim().startsWith('//') ||
                   response.trim().startsWith('import');

    outputContent.innerHTML = `
      <div class="pg-response ${isCode ? 'pg-response-code' : ''}">
        <pre><code>${_escapeHtml(response)}</code></pre>
      </div>
    `;

    if (outputMeta) {
      outputMeta.innerHTML = `
        <span class="pg-meta-item">${tokens} tokens</span>
        <span class="pg-meta-item">${time}s</span>
        <span class="pg-meta-item">${selectedTool.name}</span>
      `;
    }

    // Animate response
    gsap.from('.pg-response', {
      y: 10,
      opacity: 0,
      duration: 0.4,
      ease: 'power2.out',
    });

    // Re-enable button
    sendBtn.disabled = false;
    sendBtn.innerHTML = `Generate <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>`;
  }, delay);
}

function _escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

function _checkUrlParams() {
  const params = new URLSearchParams(window.location.search);
  const toolId = params.get('tool');
  if (toolId) {
    _selectTool(toolId);
    // Highlight in sidebar
    const btn = document.querySelector(`[data-tool-id="${toolId}"]`);
    if (btn) btn.classList.add('active');
  }
}
